### ISSUE TITLE
Missing variables, please update the code 

### ISSUE THREAD

**Issue by Yasmin-Kassim** [NoviceMAn-prog/MSRF-Net#5]
Inside msrf.py, the sau function has two missed variables (att and pred8). Those variables are missed and the code needs to be updated and corrected.
![image](https://user-images.githubusercontent.com/16782894/139754934-374b6f69-23b8-4c2a-8f61-d1b4a9bd1b4b.png)

The other issue that I found is when I import sau from msrf, I got this error, please advise, I believe it is a bug in the code as well

Traceback (most recent call last):
  File "C:/Users/Username/MSRF-Net-main/train.py", line 82, in <module>
    from msrf import sau
  File "C:/Users/Username/MSRF-Net-main/msrf.py", line 200, in <module>
    edge_x_val  =  np.expand_dims(edge_x_val,axis=3)
  File "<__array_function__ internals>", line 5, in expand_dims
  File "C:\Users\Username\Anaconda3\envs\deepcell-gpu\lib\site-packages\numpy\lib\shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
  File "C:\Users\Username\Anaconda3\envs\deepcell-gpu\lib\site-packages\numpy\core\numeric.py", line 1358, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "C:\Users\Username\Anaconda3\envs\deepcell-gpu\lib\site-packages\numpy\core\numeric.py", line 1358, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 3 is out of bounds for array of dimension 2

**Comment by ogladkov** [comment]
Just bumped into the same problem. Please update the code.

**Comment by NSAVALAN** [comment]
Hi all,

I have the same problem! would you please share the solution here if you corrected it!

**Comment by Wangbenzhi** [comment]
The same problem, hope owner could update the code.

**Comment by puzhong-hug** [comment]
The same problem, hope owner could update the code,too.

**Comment by NoviceMAn-prog** [comment]
The code is now updated, all the mentioned issues are resolved
